### PR TITLE
Updates to selectize menu css and analytics capturing

### PR DESCRIPTION
**Pull request by shua123**
@versatilehuman Are you okay if I push these updates to production? This encompasses the fixes for https://github.com/smartchicago/trailsy/issues/193 and https://github.com/smartchicago/trailsy/issues/196 along with some additional analytics event tracking.

### CODE REVIEW

**Comment by versatilehuman** [comment]
Looks good, let's do it.

**Comment by shua123** [comment]
These updates are now live.

**Comment by versatilehuman** [comment]
JS changes look good, I'm not getting newguts.css updates (cleared cache, tried private browser) from 061a518.

**Comment by shua123** [comment]
Try now

**Comment by versatilehuman** [comment]
Looks good.

**Pull request merged**
